// Re-exported from @firestartorg/secure-exec-nodejs — canonical source is packages/nodejs/src/isolate-bootstrap.ts
export type {
	NodeExecutionDriverOptions,
	BudgetState,
	DriverDeps,
} from "@firestartorg/secure-exec-nodejs/internal/isolate-bootstrap";
export {
	DEFAULT_BRIDGE_BASE64_TRANSFER_BYTES,
	DEFAULT_ISOLATE_JSON_PAYLOAD_BYTES,
	MIN_CONFIGURED_PAYLOAD_BYTES,
	MAX_CONFIGURED_PAYLOAD_BYTES,
	PAYLOAD_LIMIT_ERROR_CODE,
	RESOURCE_BUDGET_ERROR_CODE,
	DEFAULT_SANDBOX_CWD,
	DEFAULT_SANDBOX_HOME,
	DEFAULT_SANDBOX_TMPDIR,
	PayloadLimitError,
	normalizePayloadLimit,
	getUtf8ByteLength,
	getBase64EncodedByteLength,
	assertPayloadByteLength,
	assertTextPayloadSize,
	createBudgetState,
	checkBridgeBudget,
	parseJsonWithLimit,
	getExecutionTimeoutMs,
	getTimingMitigation,
	polyfillCodeCache,
	polyfillNamedExportsCache,
	hostBuiltinNamedExportsCache,
	hostRequire,
	isValidExportName,
	getHostBuiltinNamedExports,
} from "@firestartorg/secure-exec-nodejs/internal/isolate-bootstrap";
